title: PJW
author: Phil Waymouth
email: phil+blog@waymouth.name


theme: minima

# social links
twitter_username: philwaymouth # DO NOT include the @ character, or else the build will fail!
github_username:  philwaymouth # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
